[project]
name = "timeseries-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "adwinugroho", email = "adwinnugroho16@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "statsmodels>=0.15.0",
]

[project.scripts]
timeseries-app = "timeseries-app:main"


[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
